export const endpoints = {
  auth: {
    register: '/register',
    login: '/login',
    refreshToken: '/refresh',
    forgotPassword: '/forgotPassword',
    resetPassword: '/resetPassword',
    verify2fa: '/manage/2fa',
    enable2fa: '/manage/2fa',
    info: '/manage/info',
    logout: '/logout',
    revokeToken: '/revoke',
    auditLogs: '/Authentication/audit-logs',
    userAuditLogs: (userId: string) => `/Authentication/audit-logs/user/${userId}`,
  },
  security: {
    blockedIps: '/Security/blocked-ips',
    blockIp: '/Security/block-ip',
    unblockIp: '/Security/unblock-ip',
    unlockAccount: '/Security/unlock-account',
  },
  permissions: {
    base: '/Permissions',
    byId: (id: number) => `/Permissions/${id}`,
    byRole: (roleId: string) => `/Permissions/role/${roleId}`,
    assign: '/Permissions/assign',
    remove: '/Permissions/remove',
  },
  roles: {
    base: '/api/identity/roles',
    byId: (roleId: string) => `/api/identity/roles/${encodeURIComponent(roleId)}`,
    byUser: (userId: string) => `/api/identity/users/${userId}/roles`,
    assign: (userId: string) => `/api/identity/users/${userId}/roles`,
    remove: '/Roles/remove',
  },
  users: {
    base: '/api/identity/users',
    byId: (userId: string) => `/api/identity/users/${userId}`,
  },
} as const;
